services:
  - type: web
    name: AIwebsite-genstl
    env: python
    region: oregon
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DOUBAO_API_KEY
        sync: false
